
export interface Anime {
  anime: string;
  anime_url: string;
  anime_img: string;
  episodes: number;
  votes: number;
  weight: number;
  rate: number;
  rate_1: number;
  rate_2: number;
  rate_3: number;
  rate_4: number;
  rate_5: number;
  genre_action: number;
  genre_adventure: number;
  genre_comedy: number;
  genre_drama: number;
  genre_family: number;
  genre_fantasy: number;
  genre_food: number;
  genre_harem: number;
  genre_historical: number;
  genre_horror: number;
  genre_idols: number;
  genre_isekai: number;
  genre_jdrama: number;
  genre_magical_girls: number;
  genre_martial_arts: number
  genre_mecha: number;
  genre_music: number;
  genre_mystery: number;
  genre_post_apocalyptic: number;
  genre_romance: number;
  genre_sci_fi: number;
  genre_seinen: number;
  genre_sgdrama: number;
  genre_shojo: number;
  genre_shonen: number;
  genre_slice_of_life: number;
  genre_sports: number;
  genre_supernatural: number;
  genre_thriller: number;
}
